### PR TITLE
Nyt clone

### PR DESCRIPTION
**Pull request by Oxford-G**
This is Project Sneak Peaks. Cloning of the New York Times Website.

**REASON WHY I CHANGED MY PULL REQUEST**

I was directed by Mario Enrique Delgado Naranjo(TSE) to rename my branch, which I did.
I don't have the former pull request because I deleted it after I renamed it.
Here are the screenshots of his instructions.
Screenshot_2020-10-30_18-23-24
Screenshot_2020-10-30_18-24-38

### CODE REVIEW

**Comment by uryelah** [comment]
Hi @Oxford-G, sadly I have to mark this PR as invalid for the reason below:

This is not the same PR in which you had your previous reviews for this project.
Please always ask for Code Reviews from in the same Pull Request you had your previous reviews at. 
If it's really needed to open a new Pull Request always explain in the PR message the reason why the new PR was opened and include the link to the previous one in it.

Kindly request a new code review when the problem mentioned above is fixed.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

I must commend your efforts so far. However, there are few things to correct.

- [x] There's is no **```editor's picks```** and **```most popular```** section in your design, kindly add them.

- [x] In the **```theory of inflation```** section, there's no information within the images, there should one.

- [x] Your footer should stick to the bottom of the webpage. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)). However, If you need clarification on this, do reach out on slack, @Inyama, Uchechukwu Henry

- [x] In your Html file, any section that is not inside the navigation and footer section should be placed within the main tag
  [semantic Html](https://www.w3schools.com/html/html5_semantic_elements.asp)
. 

#### That is it, when you are done with the changes, submit another form for a code review. 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

The changes that were requested haven't been implemented. Kindly do so, then submit another form for a code review.

If you need clarifications, do reach me on slack. @uche-inyama 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by Oxford-G** [comment]
Hello Uche
9:13
<https://microverse-students.slack.com/archives/D01DJR6UGVC/p1604132026001200>
I am reaching out to you because of the instructions you gave in the
project review (edited)
9:14
<https://microverse-students.slack.com/archives/D01DJR6UGVC/p1604132097002500>
I have tried to put the Aside section but it is distorting my code ... I am
working alone on the project.
9:16
<https://microverse-students.slack.com/archives/D01DJR6UGVC/p1604132185003900>
I just cannot seem to get the code right. I also don't understand what you
mean by my footer being sticky
9:17
<https://microverse-students.slack.com/archives/D01DJR6UGVC/p1604132264004600>
I have really tried my best in this project

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello great work implementing the requested changes! 🎖️  however some changes were not implemented yet.

Changes Required 🔴 

- [x] As stated on a previous review your commit messages need to be descriptive and meaningful, I see no changes on your commit messages, please refer to the links I provided before to see how to edit/merge commit messages.

- [x] Your CSS need to be cleaned, remember to keep your code DRY. (Don't repeat yourself) for example `display: inline;` is repeated 12 times. Instead of having repeated rules create a class to use on all element requiring that rule. (There are more repeated rules like: `margin-left: auto;` `margin-right: auto;` `display: flex;`) Please clean up your CSS from repeated rules.

After making the required changes please re-submit your project for another review. Cheers! 👍 

Code review by Mario Enrique Delgado Naranjo

**Review by MarioDena — APPROVED** [review]
Hello! Great work implementing the requested changes! 👍 

The project is approved. 

Warning 🟡 

Please remember to avoid repetition on your commit messages, instead of `clean up styles` several times write something like `clean up styles - description` where description is a small description of where the changes were made.

If this were a first review I would have requested the changes as mandatory. But since you already learned and made improvements to your commit messages I don't want to hold you down. However I recommend on future projects to write clear, meaningful commit messages and avoid repetition.  


Code review by Mario Enrique Delgado Naranjo.

**Review by MarioDena — APPROVED** [review]
Project approved. Read warning above.

**Pull request merged**
